#
# Copyright 1989, 1990 Eric Ng
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty whatsoever, without even the implied warranties
# of merchantability or fitness for a particular purpose.  See the
# accompanying GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to:
#
# Free Software Foundation, Inc.
# 675 Massachusetts Avenue
# Cambridge, Massachusetts 02139
#

# Turbo Pascal Directory
!if !$d(TURBO)
TURBO=C:\TP
!endif

# Makefile for egaint (for use with Turbo Make 2.0)
egaint.exe: egaint.pas driver.tpu fonts.tpu pal.exe
	tpc /m egaint.pas

pal.exe: pal.pas driver.tpu
	tpc /m pal.pas

fonts.tpu: fonts.pas sans.obj litt.obj
	tpc fonts.pas
sans.obj: $(TURBO)\sans.chr
	binobj $(TURBO)\sans.chr sans.obj SansSerifFontProc
litt.obj: $(TURBO)\litt.chr
	binobj $(TURBO)\litt.chr litt.obj SmallFontProc

driver.tpu: driver.pas egavga.obj herc.obj
	tpc driver.pas
egavga.obj: $(TURBO)\egavga.bgi
	binobj $(TURBO)\egavga.bgi egavga.obj EgaVgaDriver
herc.obj: $(TURBO)\herc.bgi
	binobj $(TURBO)\herc.bgi herc.obj HercDriver

