#
# Copyright 1989, 1990 Eric Ng
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty whatsoever, without even the implied warranties
# of merchantability or fitness for a particular purpose.  See the
# accompanying GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to:
#
# Free Software Foundation, Inc.
# 675 Massachusetts Avenue
# Cambridge, Massachusetts 02139
#

# Makefile for egaint 0.94.13 (for use with Turbo Make 2.0)
egaint.exe: eg9413.pas driver.tpu fonts.tpu
	tpc /m eg9413.pas
	copy egaint.exe eg.exe		# all this because I've been
	copy eg9413.exe egaint.exe	# having problems using rename
	erase eg9413.exe		# with Turbo Make 2.0

fonts.tpu: fonts.pas sans.obj litt.obj
	tpc fonts.pas
sans.obj: sans.chr
	binobj sans.chr sans.obj SansSerifFontProc
litt.obj: litt.chr
	binobj litt.chr litt.obj SmallFontProc

driver.tpu: driver.pas egavga.obj herc.obj
	tpc driver.pas
egavga.obj: egavga.bgi
	binobj egavga.bgi egavga.obj EgaVgaDriver
herc.obj: herc.bgi
	binobj herc.bgi herc.obj HercDriver

